import Goose from "@/components/Goose";
import Navbar from "@/components/Navbar";
import Head from "next/head";

export default function Custom500() {
  return (
    <>
      <Head>
        <title>Home | Western Rank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={"overflow-hidden flex flex-col h-screen"}>
        <Navbar className="z-10 bg-transparent" />
        <div className="flex-grow h-full flex items-center justify-center pb-20">
          <Goose className="light h-[500px] w-[500px] stroke-1 stroke-muted-foreground opacity-40">
            <div className="w-full px-20">
              <h1 className="text-6xl font-bold text-transparent bg-clip-text bg-gradient-to-br from-purple-600 to-blue-400">
                HONK!
              </h1>
              <h2 className="text-xl">
                (Translation: <span className="font-bold">500</span> Error)
              </h2>
            </div>
          </Goose>
        </div>
      </div>
    </>
  );
}
