import NavbarHeader from "@/components/NavbarHeader";
import { DataTable } from "@/components/data-table";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { Skeleton } from "@/components/ui/skeleton";
import { roundToNearest } from "@/lib/utils";
import { useInfiniteQuery } from "@tanstack/react-query";
import { ColumnDef } from "@tanstack/react-table";
import { Compass } from "lucide-react";
import Head from "next/head";
import { type GetCoursesResponse } from "./api/courses";

type ExploreCourseRow = {
  courseCode: string;
  ratingsCount: number;
  likedPercent: string;
  difficulty: string;
  attendancePercent: string;
};

const columns: ColumnDef<ExploreCourseRow | undefined>[] = [
  {
    accessorKey: "courseCode",
    header: "Course Code",
  },
  {
    accessorKey: "ratingsCount",
    header: "Ratings",
  },
  {
    accessorKey: "likedPercent",
    header: "Liked",
  },
  {
    accessorKey: "difficulty",
    header: "Difficulty",
  },
  {
    accessorKey: "attendancePercent",
    header: "Attendance",
  },
];

function generateCourseRow(course: GetCoursesResponse["courses"][0]): ExploreCourseRow | undefined {
  return {
    courseCode: course.course_code,
    ratingsCount: course._count?.review_id ?? 0,
    likedPercent: roundToNearest(course._count?.liked ?? 0, 0) + "%",
    difficulty: `${roundToNearest((course._avg?.difficulty ?? 0) / 2, 1)}/5`,
    attendancePercent: roundToNearest(course._avg?.attendance ?? 0, 0) + "%",
  };
}

const ExplorePage = () => {
  const {
    data: coursesData,
    error,
    fetchPreviousPage,
    fetchNextPage,
    hasNextPage,
    isFetching,
    isFetchingNextPage,
    status,
    isSuccess,
  } = useInfiniteQuery({
    queryKey: ["explore-courses"],
    queryFn: async ({ pageParam = 0 }) => {
      const searchParams = new URLSearchParams({
        cursor: pageParam,
        sortkey: "liked",
        sortorder: "desc",
      });

      const response = await fetch(`/api/courses?${searchParams.toString()}`);
      if (!response.ok) throw new Error("Courses were not found");
      const coursesData: GetCoursesResponse = await response.json();
      const courses = coursesData.courses.map((course) => generateCourseRow(course));
      return {
        ...coursesData,
        courses,
      };
    },
    getNextPageParam: (lastPage) => lastPage.next_cursor,
  });

  return (
    <>
      <Head>
        <title>Explore Courses | Western Rank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col min-h-screen">
        <NavbarHeader
          heading="Explore Courses"
          subHeading={`See all ${coursesData?.pages[0]._count} Western University Courses`}
          Icon={Compass}
          searchBar
          sticky
          className="h-10 pt-6"
        />
        <div className="flex flex-col md:flex-row gap-2 light text-primary bg-background py-4 px-2 md:px-8 lg:px-15 xl:px-40 flex-grow">
          <div className="flex flex-col h-[58vh]">
            {isSuccess && (
              <DataTable
                columns={columns}
                data={coursesData?.pages?.flatMap((page) => page?.courses)}
              />
            )}
            {!isSuccess && <Skeleton className="flex-1 w-full h-full" />}
            <div className="py-2 flex justify-between w-full">
              <Button onClick={() => fetchPreviousPage()}>Previous</Button>
              <Button onClick={() => fetchNextPage()}>Next</Button>
            </div>
          </div>
          <Separator orientation="vertical" className="w-[1px] h-200" />
        </div>
      </div>
    </>
  );
};

export default ExplorePage;
