import Head from "next/head";

import Navbar from "../components/Navbar";
import Searchbar from "../components/Searchbar";

const Home = () => {
  return (
    <>
      <Head>
        <title>Home | Western Rank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className="min-h-screen items-center"
        style={{
          backgroundImage: "url(/College.svg), url(/College2.svg)",
          backgroundPosition: "0% 0%, 0% -320%",
          backgroundRepeat: "no-repeat",
        }}
      >
        <Navbar className="z-10 bg-transparent" />
        <div className="flex flex-col gap-8 flex-grow w-screen max-w-[100vw] px-4 md:px-10 lg:px-20 xl:px-72 py-32 lg:py-42">
          <h1 className="text-primary font-bold text-2xl md:text-3xl">
            Explore course reviews from <br />{" "}
            <span className="text-transparent bg-clip-text bg-gradient-to-br from-purple-500 to-blue-500">
              Western University
            </span>{" "}
            students
          </h1>
          <Searchbar />
        </div>
      </main>

      <footer></footer>
    </>
  );
};

export default Home;
