import type { GetServerSideProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Link from 'next/link'
import { AppBar, Toolbar, ThemeProvider, Typography, Box, Container } from '@mui/material'
import MuiLink from '@mui/material/Link'

import Navbar from '../components/Navbar'
import Searchbar from '../components/Searchbar'

const Home = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Home | Western Rank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className={styles.main}>
        <Container maxWidth="md" className={styles.container}>
          <Typography variant="h4" fontWeight={800} >
            Explore course reviews from <br/> Western University students
          </Typography>
          <Searchbar />
        </Container>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
