import Navbar from "@/components/Navbar";
import { UserReview } from "@/components/Review";
import { Separator } from "@/components/ui/separator";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { getUserByEmail } from "@/services/user";
import { Course_Review, User } from "@prisma/client";
import { User2 } from "lucide-react";
import { GetServerSideProps } from "next";
import { getServerSession } from "next-auth";
import Head from "next/head";

interface ProfileProps {
  user: User & { Course_Review: Course_Review[] };
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getServerSession(context.req, context.res, authOptions);

  if (!session || !session.user?.email) {
    return {
      redirect: {
        destination: "/api/auth/signin",
        permanent: false,
      },
    };
  }

  const user = await getUserByEmail(session.user.email);

  return {
    props: {
      user: JSON.parse(JSON.stringify(user)) as User,
    },
  };
};

function Profile({ user }: ProfileProps) {
  console.log(user.Course_Review[0]);
  return (
    <>
      <Head>
        <title>Your Profile | Western Rank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex flex-col">
        <Navbar searchBar></Navbar>
        <div className="dark bg-background text-primary border-border py-4 pt-16 px-4 md:px-8 lg:px-15 xl:px-40">
          <div className="flex flex-col">
            <User2 className="stroke-purple-400" />
            <h4 className="text-3xl font-extrabold py-1 ">Your Profile</h4>
            <h5 className="text-lg text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-blue-400 to-35%">
              {user.email}
            </h5>
          </div>
        </div>
        <div className="light text-primary bg-background flex-grow py-4 px-4 md:px-8 lg:px-15 xl:px-40">
          <h5 className="py-1 text-secondary-foreground">
            You&apos;ve made{" "}
            <span className="font-semibold">{user.Course_Review.length} reviews</span>
          </h5>
          <div className="grid lg:grid-cols-2 gap-3 py-2">
            {user.Course_Review.map((review, index) => (
              <UserReview key={index} review={review} includeCourseCode />
            ))}
          </div>
        </div>
        <Separator />
      </main>
    </>
  );
}

export default Profile;
