import Navbar from "@/components/Navbar";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { getUserByEmail } from "@/services/user";
import { Course_Review, User } from "@prisma/client";
import { GetServerSideProps } from "next";
import { getServerSession } from "next-auth";
import Head from "next/head";
import { useMemo } from "react";

interface ProfileProps {
  user: User & { Course_Review: Course_Review[] };
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getServerSession(context.req, context.res, authOptions);

  if (!session || !session.user?.email) {
    return {
      redirect: {
        destination: "/api/auth/signin",
        permanent: false,
      },
    };
  }

  const user = await getUserByEmail(session.user.email);

  return {
    props: {
      user: JSON.parse(JSON.stringify(user)) as User,
    },
  };
};

function Profile({ user }: ProfileProps) {
  const courses = useMemo(() => {
    return user.Course_Review.map((review) => review.course_code);
  }, []);
  return (
    <>
      <Head>
        <title>Home | Western Rank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen items-center">
        <Navbar searchBar></Navbar>
        <div className="dark bg-background text-primary flex flex-col h-40 py-4 pt-16 ">
          <h4 className="px-4 md:px-8 lg:px-15 xl:px-40 text-3xl font-extrabold text-transparent bg-clip-text bg-gradient-to-br from-purple-400 to-blue-800 py-1">
            {user.email}
          </h4>
          <h5 className="px-4 md:px-8 lg:px-15 xl:px-40 text-lg text-primary">
            {user.Course_Review.length} reviews
          </h5>
        </div>
        <div className="light bg-background text-primary flex-grow"></div>
      </main>
    </>
  );
}

export default Profile;
